package cst316;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextArea;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.ContextMenuEvent;

public class MarketingChoiceFXMLController implements Initializable {
	@FXML
	private TextArea descriptionBox;
	@FXML
	private ComboBox<String> dropMenu;
	@FXML
	private Button returnButton;
	@FXML
	private ImageView marketingPicture;
	@FXML
	private Button purchaseButton;
	String output;
	
	Image image = new Image("file:/../res/printM.gif");
	Image image2 = new Image("file:/../res/couponM.jpg");
	Image image3 = new Image("file:/../res/wackyM.gif");
	Image image4 = new Image("file:/../res/tvM.gif");

	// Event Listener on ComboBox[#dropMenuPotential].onAction
		@FXML
		public void dropMenuFired(ActionEvent event) {
			output = (String) dropMenu.getSelectionModel().getSelectedItem().toString();
			switch(output) {
				case "Print Marketing": 
					marketingPicture.setImage(image);
					descriptionBox.clear();
					descriptionBox.appendText("Cost: x \n");
					descriptionBox.appendText("Description: Moderately expensive and moderately reliable form of Marketing.");
					break;
				case "Coupon Marketing":
					marketingPicture.setImage(image2);
					descriptionBox.clear();
					descriptionBox.appendText("Cost: x \n");
					descriptionBox.appendText("Description: A more expensive and more reliable form of Marketing ");				; 
					break;
				case "WWITM Marketing": 
					marketingPicture.setImage(image3);
					descriptionBox.clear();
					descriptionBox.appendText("Cost: x \n");
					descriptionBox.appendText("Description: The Cheapest Marketing option, and the most unreliable. The 'Wacky Waving Inflatable Tube Man' is either hit or miss with the audience.");
					break;
				case "Television Marketing": 
					marketingPicture.setImage(image4);
					descriptionBox.clear();
					descriptionBox.appendText("Cost: x \n");
					descriptionBox.appendText("Description: The Most Expensive Marketing option, and the most reliable form of marketing.");	
					break;
			}
		}
	// Event Listener on ComboBox[#dropMenu].onContextMenuRequested
	@FXML
	public void changeMenu(ContextMenuEvent event) {};
	// Event Listener on Button[#returnButton].onAction
	@FXML
	public void returnButtonFired(ActionEvent event) {
		// TODO Autogenerated
	}
	
	//@Override
	public void initialize(URL fxmlFileLocation, ResourceBundle resources) {
		dropMenu.getItems().setAll("Print Marketing",
								   "Coupon Marketing",
								   "WWITM Marketing",
							 	   "Television Marketing");
	}
	
	
	@FXML
	public void purchaseButtonFired(ActionEvent event) {
		if(output != null) {
			switch(output) {
			case "Print Marketing": 
				System.out.println("PRINT MARKETING PURCHASED.");
				break;
			case "Coupon Marketing":
				System.out.println("COUPON MARKETING PURCHASED.");
				break;
			case "WWITM Marketing":
				System.out.println("WACKY WAVING INFLATABLE TUBE MAN MARKETING PURCHASED.");
				break;
			case "Television Marketing":
				System.out.println("TELEVISION MARKETING PURCHASED.");
				break;
			}
		}
	}
}
