package cst316;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextArea;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;

public class ResearchDevelopController implements Initializable {
	@FXML
	private ImageView returnButton;
	@FXML
	private TextArea descriptionBox;
	@FXML
	private ComboBox<String> researchChoiceBox;
	@FXML
	private ImageView pictureBox;
	@FXML
	private ComboBox<String> devChoiceBox;
	@FXML
	private ImageView purchaseButton;
	
	String outputDev;
	String outputResearch;
	
	// Event Listener on ImageView[#returnButton].onMouseClicked
	@FXML
	public void returnMouseFired(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#returnButton].onMouseEntered
	@FXML
	public void returnMouseEnter(MouseEvent event) {
		Image image = new Image("file:/../res/return_highlight.png");
		returnButton.setImage(image);
	}
	// Event Listener on ImageView[#returnButton].onMouseExited
	@FXML
	public void returnMouseExit(MouseEvent event) {
		Image image = new Image("file:/../res/return.png");
		returnButton.setImage(image);
	}
	// Event Listener on ComboBox[#researchChoiceBox].onAction
	@FXML
	public void researchChoiceButtonFired(ActionEvent event) {
		Image image = new Image("file:/../res/research_logo.png");
		pictureBox.setImage(image);
		outputResearch = (String) researchChoiceBox.getSelectionModel().getSelectedItem().toString();
		switch(outputResearch) {
		case "Research new materials": 
			descriptionBox.clear();
			descriptionBox.appendText("Cost: x \n");
			descriptionBox.appendText("Description: Researches new materials for "
					+ "your products so that they are more "
					+ "reliable an aesthetically appealing");
			break;
		case "Research new media trends": 
			descriptionBox.clear();
			descriptionBox.appendText("Cost: x \n");
			descriptionBox.appendText("Description: Researches what is currently "
					+ "trending and in style so that your products a"
					+ "ren't seen as 'old fashioned' or unappealing especially "
					+ "to the younger demographics");
			break;
		case "Research new technology": 
			descriptionBox.clear();
			descriptionBox.appendText("Cost: x \n");
			descriptionBox.appendText("Description: Researches newer and faster "
					+ "technologies for your products so that it is overall more "
					+ "effective and responsive to the end users.");
			break;
		case "Research new strategies": 
			descriptionBox.clear();
			descriptionBox.appendText("Cost: x \n");
			descriptionBox.appendText("Description: Researches new strategies for "
					+ "the employees so that they can work in a more efficient manner "
					+ "and achieve more with less time.");
			break;
		}
	}
	// Event Listener on ComboBox[#devChoiceBox].onAction
	@FXML
	public void devChoiceButtonFired(ActionEvent event) {
		Image image = new Image("file:/../res/development_logo.png");
		pictureBox.setImage(image);
		outputDev = (String) devChoiceBox.getSelectionModel().getSelectedItem().toString();
		switch(outputDev) {
		case "Develop a commercial":
			descriptionBox.clear();
			descriptionBox.appendText("Cost: x \n");
			descriptionBox.appendText("Description: Develops a commercial that "
					+ "advertises your product and allows for more people to be aware of it.");
		break;
		case "Develop a science lab":
			descriptionBox.clear();
			descriptionBox.appendText("Cost: x \n");
			descriptionBox.appendText("Description: Develop a science lab that "
					+ "increases the quality of all research that the company has invested in.");
		break;
		}
	}
	// Event Listener on ImageView[#purchaseButton].onMouseClicked
	@FXML
	public void purchaseButtonFired(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#purchaseButton].onMouseEntered
	@FXML
	public void purchaseEnter(MouseEvent event) {
		Image image = new Image("file:/../res/purchase_highlight.png");
		purchaseButton.setImage(image);
	}
	// Event Listener on ImageView[#purchaseButton].onMouseExited
	@FXML
	public void purchaseExit(MouseEvent event) {
		Image image = new Image("file:/../res/purchase.png");
		purchaseButton.setImage(image);
	}
	
	@Override
	public void initialize(URL fxmlFileLocation, ResourceBundle resources) {
		researchChoiceBox.getItems().setAll("Research new materials",
											"Research new media trends",
											"Research new technology",
											"Research new strategies");
		devChoiceBox.getItems().setAll("Develop a commercial",
									   "Develop a science lab");
	}
}
