package application;

import java.util.ArrayList;

import cst316.MarketCompany;
import cst316.Player;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.chart.PieChart;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.layout.AnchorPane;

public class PieChartFromArrayController extends AnchorPane {
	@FXML
	private AnchorPane AnchorPane;
	@FXML
	private Button returnButton;
	@FXML
	private PieChart piechart;
	@FXML
	private Button Button1;
	@FXML
	private Button Button2;
	@FXML
	private Button Button3;
	@FXML
	private Button Button4;
	@FXML
	private Button Button5;
	
	//Declaring local variables to be used in the Marketing Statistics Display
	String output;
	Main application;
	Player player;
	
	static MarketCompany mcSample1 = new MarketCompany("Wendys", 15.5);
	static MarketCompany mcSample2 = new MarketCompany("BurgerKing", 35.9);
	static MarketCompany mcSample3 = new MarketCompany("McDonalds", 75.9);
	
	static MarketCompany mcSample4 = new MarketCompany("Taylor Swift", 35.6);
	static MarketCompany mcSample5 = new MarketCompany("Pharrel Williams", 44);
	static MarketCompany mcSample6 = new MarketCompany("Tupac Shakur", 103.3);
	static MarketCompany mcSample7 = new MarketCompany("Kendrick Lamar", 77.7);
	static MarketCompany mcSample8 = new MarketCompany("Pink Floyd", 11.9);

	ArrayList<MarketCompany> companyList = new ArrayList<MarketCompany>();


	// Event Listener on Button[#Button1].onAction
	@FXML
	public void button1Fired(ActionEvent event) {
		companyList.add(mcSample1);
		companyList.add(mcSample2);
		companyList.add(mcSample3);
		
		ObservableList<PieChart.Data> pieChartData =
                FXCollections.observableArrayList(
                		//for (int z = 0; z < companyList.size(); z ++){
					new PieChart.Data((companyList.get(1)).getName(), (companyList.get(1)).getMarketPower()),
					new PieChart.Data((companyList.get(2)).getName(), (companyList.get(2)).getMarketPower()),
					new PieChart.Data((companyList.get(3)).getName(), (companyList.get(3)).getMarketPower()));
			        piechart.setTitle("Fast Food Market Report");
			        piechart.setData(pieChartData);
	}
	// Event Listener on Button[#Button2].onAction
	@FXML
	public void button2Fired(ActionEvent event) {
		ObservableList<PieChart.Data> pieChartData =
                FXCollections.observableArrayList(
                		//for (int z = 0; z < companyList.size(); z ++){
					new PieChart.Data((companyList.get(4)).getName(), (companyList.get(4)).getMarketPower()),
					new PieChart.Data((companyList.get(5)).getName(), (companyList.get(5)).getMarketPower()),
					new PieChart.Data((companyList.get(6)).getName(), (companyList.get(6)).getMarketPower()),
					new PieChart.Data((companyList.get(7)).getName(), (companyList.get(7)).getMarketPower()),
					new PieChart.Data((companyList.get(8)).getName(), (companyList.get(8)).getMarketPower()));
			        piechart.setTitle("Pop Music Charts Top 100 Report");
			        piechart.setData(pieChartData);
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button3].onAction
	@FXML
	public void button3Fired(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button4].onAction
	@FXML
	public void button4Fired(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button5].onAction
	@FXML
	public void button5Fired(ActionEvent event) {
		// TODO Autogenerated
	}
	
	//@Override
	public void setApp(Main app) {
		application = app;
		this.player = application.getPlayer();
	}
	
	public void setPlayer(Player player) {
		this.player = player;
	}

	// Event Listener on Button[#returnButton].onAction
	@FXML
	public void returnButtonFired(ActionEvent event) throws Exception {
		LandingController ctr = (LandingController) application.replaceSceneContent("Landing.fxml", LandingController.class);
		ctr.setApp(application);
	}
}
