package application;

import java.io.InputStream;
import java.net.URL;
import java.util.ArrayList;
import java.util.ResourceBundle;

import cst316.Investment;
import cst316.Player;
import javafx.fxml.FXML;
import javafx.scene.control.TextArea;
import javafx.scene.control.ComboBox;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;

public class ProductManagementController extends AnchorPane  {
    @FXML
    private ResourceBundle resources;
    @FXML
    private URL location;
	@FXML
	private ImageView returnButton;
	@FXML
	private ImageView purchaseButton;
	@FXML
	private TextArea descriptionField;
	@FXML
	private ComboBox comboBox;
	@FXML
	private ImageView replacableImage;

	Image retIn;
	Image retOut;

	private Player player;
	private Main application;
	InputStream in;	
	
	public void setApp(Main app){
		application = app;
		this.player = application.getPlayer();
	}	
	
	// Event Listener on ImageView[#returnButton].onMouseClicked
	@FXML
	public void returnMouseClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#returnButton].onMouseEntered
	@FXML
	public void returnMouseEntered(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#returnButton].onMouseExited
	@FXML
	public void returnMouseExited(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#purchaseButton].onMouseClicked
	@FXML
	public void purchaseMouseClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#purchaseButton].onMouseEntered
	@FXML
	public void purchaseMouseEntered(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#purchaseButton].onMouseExited
	@FXML
	public void purchaseMouseExited(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#comboBox].onMouseClicked
	@FXML
	public void comboBoxMouseClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	public void setPlayer(Player player) {
		this.player = player;
	}
}
