package application;

import java.util.ArrayList;

import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.ContextMenuEvent;
import cst316.MarketCompany;
import cst316.Player;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.chart.PieChart;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.image.ImageView;
import javafx.scene.layout.AnchorPane;

public class QuickStartController extends AnchorPane {
	@FXML
	private AnchorPane AnchorPane;
	@FXML
	private Button returnButton;
	@FXML
	private ImageView guideImage;
	@FXML
	private Button Button1;
	@FXML
	private Button Button2;
	@FXML
	private Button Button3;
	@FXML
	private Button Button4;
	@FXML
	private Button Button5;
	
	//Declaring local variables to be used in the Marketing Statistics Display
	String output;
	Main application;
	Player player;

	
    Image image1 = new Image(Market3Controller.class.getClassLoader().getResourceAsStream("res/cst316quickstart-0.png"));
    Image image2 = new Image(Market3Controller.class.getClassLoader().getResourceAsStream("res/cst316quickstart-1.png"));
    Image image3 = new Image(Market3Controller.class.getClassLoader().getResourceAsStream("res/cst316quickstart-2.png"));
    Image image4 = new Image(Market3Controller.class.getClassLoader().getResourceAsStream("res/cst316quickstart-3.png"));
	

	// Event Listener on Button[#Button1].onAction
	/**
	 * @param event
	 */
	@FXML
	public void button1Fired(ActionEvent event) {
		guideImage.setImage(image1);
	}
	// Event Listener on Button[#Button2].onAction
	/**
	 * @param event
	 */
	@FXML
	public void button2Fired(ActionEvent event) {
		guideImage.setImage(image2);
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button3].onAction
	/**
	 * @param event
	 */
	@FXML
	public void button3Fired(ActionEvent event) {
		guideImage.setImage(image3);
		// TODO Autogenerated
	}
	// Event Listener on Button[#Button4].onAction
	/**
	 * @param event
	 */
	@FXML
	public void button4Fired(ActionEvent event) {
		guideImage.setImage(image4);
		
	}
	// Event Listener on Button[#Button5].onAction
	/**
	 * @param event
	 */
	@FXML
	public void button5Fired(ActionEvent event) {

	}
	
	//@Override
	/**
	 * @param app
	 */
	public void setApp(Main app) {
		application = app;
		this.player = application.getPlayer();
	}
	
	/**
	 * @param player
	 */
	public void setPlayer(Player player) {
		this.player = player;
	}

	// Event Listener on Button[#returnButton].onAction
	/**
	 * @param event
	 * @throws Exception
	 */
	@FXML
	public void returnButtonFired(ActionEvent event) throws Exception {
		LandingController ctr = (LandingController) application.replaceSceneContent("Landing.fxml", LandingController.class);
		ctr.setApp(application);
	}
}
