package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextArea;

import javafx.scene.layout.AnchorPane;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class TEST {
	@FXML
	private AnchorPane anchorPane;
	@FXML
	private ImageView returnBtn;
	@FXML
	private TextArea pointsText;
	@FXML
	private TextArea employeesText;
	@FXML
	private TextArea moneyText;
	@FXML
	private TextArea assetsText;
	@FXML
	private TextArea investmentsText;
	@FXML
	private TextArea productText;

	// Event Listener on ImageView[#returnBtn].onMouseClicked
	@FXML
	public void onReturnMouseClick(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#returnBtn].onMouseEntered
	@FXML
	public void onReturnMouseEnter(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#returnBtn].onMouseExited
	@FXML
	public void onReturnMouseExit(MouseEvent event) {
		// TODO Autogenerated
	}
}
